apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJY1Rqd0UwelRPc0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1qQXlNRE01TWpCYUZ3MHpOREE0TVRneU1EUTBNakJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURwWWxta2w3bW5SY2dGZXFRcjBKTlFSNXl1QW9ZVHI4MDN6OXRKekpUR3pEMlhYZjJoNkkrYUNOeVQKNHRiSVQwZkxWb2tuc290SmJhMDQ2Vm9xUjgzd1RwSUk0c2VUQWRYMmQ0VWpPMEhCYmVCVlIrNE5weUdXZFI4cQphZ2RXdW40UWpqWjBJeXI4TSsyWDdCSnNVejBaVk1rSVdrWHY0VHdsZWRaVzFQYVhkbkZkbVMxdElLdnZ0dkRCCkRMSGNIeXh1akZndG9JQUU5U3ROQXFSazZBbXVEckdiK2pMSWhKcGpWMkdTVFN1ZHZtR2NEOEF4ZGprTXhFRm8KTXc0WVVtTHJDNVR1akhJMDhkVDdsMWIvNzVhSDkwU1pIMGQ2YmM2SWd6NzJrcVRKRGM1RVRndWYwYXJycTdpYgpjRlBZWmc0L281MDdTajhOWEw5Z09menJzSmNCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRaitrS1IyWTM5Q1daQmJ0eXFMWWxKU2xyU3pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ01EcGt0cVFabgp3eFNWSzFlZ2l4dlpOVC9NSVl0U3F2d3R3bE1DYXlIS3EyUHQ4V3FaZ0lwUzBTdXVBM3pwbUpBdFNkQmVXUkpECnBjT1RVc2xMN1V1OEYvMStMb3dlVmE0OUV6SHFBdjRXOG5DOUtMOVI2UlJORVJTUWtFSGRuS0k4RlVJZVJQMjcKUUJDT05BRFNNS3F3Smt0QzF0eEREdHhQTERxQVM4UmFpa3JuRUdnUFR5VjhZdTYrd085b202Q2d6eFd5SGVwUApxRHBKRlAzOXlQWVg0OTZpbDI4YlZ4MDVFckZUakVBZnY1T1RyVFgvQWJuV2FFWTZ4MGlWOGpKTDhuOUJMbFZYCk9kV1psL212RkY3bTF4amlDbnE4c3NZZVJqQ2lOUUhQWFRqZm1vbzdPckxvUThNQUtRTTBuNkFva3h4ZjlNei8KQVpma0lzQTBuUjhkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://84BFA456B893FAAA9984C47688CBA888.gr7.ap-southeast-1.eks.amazonaws.com
  name: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
contexts:
- context:
    cluster: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
    user: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
  name: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
current-context: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-southeast-1:248189921237:cluster/project-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-southeast-1
      - eks
      - get-token
      - --cluster-name
      - project-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
