apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: LoadBalancer
  ports:
    - port: 80         # External port to access your service
      targetPort: 4499 # Internal port where your application is listening
  selector:
    app: wisecow      # Make sure this matches the label of your pods

